version: '3'

services:

  jobaggrv-mysql:
    image: mysql:8-debian
    environment:
      MYSQL_ROOT_PASSWORD: jobaggrv
      MYSQL_USER: jobaggrv
      MYSQL_PASSWORD: jobaggrv
      MYSQL_DATABASE: jobaggrv
    ports:
      - 33060:3306
    volumes:
      - "db-vol:/var/lib/mysql:rw"
  
  jobaggrv-scrapy:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - './JobAggrV/conf/config.ini.example:/opt/jobaggrv/JobAggrV/conf/config.ini' 
volumes:
  db-vol:
